# Generated by Django 3.2.13 on 2022-05-28 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_logged_id',
            field=models.BooleanField(default=False),
        ),
    ]
